# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e2e6d23790891bfe4312b1f6231d5944dd9eee843bea1868d1c13b552dc2cfddc55d05a8b0c8506a1946396b7c4195a9d119a1d4402441807efa5dbd34a9b1

test:
  secret_key_base: 98e0d40c26b6af20b1cd225f08fe019fbae71dc529657112c08f9f5d47ee60b247189153da046c6e8318b5eac9a47c629edb040cfb0c504fb57496dd7b3a7126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
